// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuejpzjykhbkrjrfdyol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1ZWpwemp5a2hia3JqcmZkeW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODM0MzMsImV4cCI6MjA1MjA1OTQzM30.oWmlyLvFHEfa6HEH8eHWHe7_bq3SGoABG7Hl78UUs6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);